# Generated by Django 4.2.28 on 2026-02-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'address_type', 'is_default'], name='user_addres_user_id_0db695_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['user_id'], name='admin_audit_user_id_d152c5_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['model', '-timestamp'], name='admin_audit_model_da1de5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'updated_at'], name='cart_items_user_id_3e240a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_595d11_idx'),
        ),
    ]
