# Generated by Django 5.2.11 on 2026-02-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('password', 'Password')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('database', 'Database'), ('email', 'Email'), ('payment', 'Payment Gateway'), ('security', 'Security'), ('general', 'General'), ('social', 'Social Auth'), ('redis', 'Redis/Cache')], default='general', max_length=20)),
                ('is_secret', models.BooleanField(default=False, help_text='Hide value in admin (for passwords, keys)')),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'ordering': ['category', 'key'],
            },
        ),
    ]
