# Generated by Django 5.2.11 on 2026-02-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile version', null=True, upload_to='hero/')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('discord', 'Discord')], max_length=20, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fab fa-facebook)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['sort_order', 'platform'],
            },
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='category',
            field=models.CharField(choices=[('database', 'Database'), ('email', 'Email'), ('payment', 'Payment Gateway'), ('security', 'Security'), ('general', 'General'), ('social', 'Social Auth'), ('redis', 'Redis/Cache'), ('storage', 'Storage')], default='general', max_length=20),
        ),
    ]
