# Generated by Django 4.2.28 on 2026-02-18 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_first_order_only', models.BooleanField(default=False)),
                ('applicable_categories', models.JSONField(blank=True, default=list)),
                ('applicable_products', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True, unique=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_distribution', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'review_summaries',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('helpful_users', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=True)),
                ('admin_response', models.TextField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_reviews',
                'ordering': ['-helpful_count', '-created_at'],
                'indexes': [models.Index(fields=['product_id'], name='product_rev_product_98782c_idx'), models.Index(fields=['user_email'], name='product_rev_user_em_750f58_idx'), models.Index(fields=['rating'], name='product_rev_rating_fb8943_idx'), models.Index(fields=['created_at'], name='product_rev_created_1dfa58_idx')],
            },
        ),
        migrations.CreateModel(
            name='LimitedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('flash_sale', 'Flash Sale'), ('deal_of_day', 'Deal of the Day'), ('weekend_special', 'Weekend Special'), ('clearance', 'Clearance')], default='flash_sale', max_length=20)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('category_ids', models.JSONField(blank=True, default=list)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_prices', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('banner_image', models.URLField(blank=True, max_length=500)),
                ('banner_text', models.CharField(blank=True, max_length=100)),
                ('banner_color', models.CharField(default='red', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_countdown', models.BooleanField(default=True)),
                ('show_banner', models.BooleanField(default=True)),
                ('max_items', models.PositiveIntegerField(default=0)),
                ('items_sold', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'limited_offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='limited_off_slug_8f30fc_idx'), models.Index(fields=['is_active'], name='limited_off_is_acti_320fc4_idx'), models.Index(fields=['starts_at', 'ends_at'], name='limited_off_starts__d4ebfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('order_number', models.CharField(max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='offers.coupon')),
            ],
            options={
                'db_table': 'coupon_usage',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_is_acti_dbb3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_until'], name='coupons_valid_u_bf1c18_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user_email'], name='coupon_usag_coupon__c90aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['order_number'], name='coupon_usag_order_n_08d4b7_idx'),
        ),
    ]
