# Generated by Django 4.2.28 on 2026-02-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
