# Generated by Django 4.2.28 on 2026-02-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_productreview_videos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user_email', 'used_at'], name='coupon_usag_user_em_bb760b_idx'),
        ),
        migrations.AddIndex(
            model_name='limitedoffer',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='limited_off_is_acti_8838e7_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['is_approved'], name='product_rev_is_appr_dbd189_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_value__gte', 0)), name='coupon_discount_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('min_order_value__gte', 0)), name='coupon_min_order_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('max_discount__gte', 0)), name='coupon_max_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='coupon_usage_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='limitedoffer',
            constraint=models.CheckConstraint(check=models.Q(('discount_value__gte', 0)), name='limited_offer_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_review_rating_range'),
        ),
    ]
