# Generated by Django 5.2.11 on 2026-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_couponusage_coupon_usag_user_em_bb760b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
