# Generated by Django 4.2.28 on 2026-02-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='category_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['deleted_at'], name='products_deleted_c3f9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'deleted_at'], name='products_is_acti_e759f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_status', 'is_active'], name='products_product_9d7f81_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('compare_price__gte', 0), ('compare_price__isnull', True), _connector='OR'), name='product_compare_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_per_item__gte', 0), ('cost_per_item__isnull', True), _connector='OR'), name='product_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__isnull', True), _connector='OR'), name='product_weight_non_negative'),
        ),
    ]
